name: continuous-integration/github/pr/osx

on:
  pull_request:
    branches:
      - master
      # Can add additional branches if desired

jobs:
  pyomo-mac-tests:
    name: py${{ matrix.python-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8] # All available Python versions

    steps:
    - uses: actions/checkout@v1 # Checkout branch(es)
    - name: Set up Python ${{ matrix.python-version }} # Initialize Python version
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pyomo dependencies
      run: |
        echo "Install pre-dependencies for pyodbc..."
        brew update # Install pre-dependencies for pyodbc
        brew install bash gcc
        brew link --overwrite gcc
        brew install pkg-config
        brew install unixodbc
        brew install freetds # Now install Python modules
        python -m pip install --upgrade pip
        echo ""
        echo "Install Pyomo dependencies..."
        echo ""
        pip install cython numpy scipy ipython openpyxl sympy pyyaml pyodbc networkx xlrd pandas matplotlib dill seaborn pymysql pyro4 pint pathos
        echo ""
        echo "Install GAMS..."
        echo ""
        wget -q https://d37drm4t2jghv5.cloudfront.net/distributions/29.1.0/macosx/osx_x64_64_sfx.exe
        chmod +x osx_x64_64_sfx.exe
        ./osx_x64_64_sfx.exe -q -d gams
        cd gams/gams29.1_osx_x64_64_sfx/apifiles/Python/
        y_ver=$(python -c 'import sys;print("%s%s" % sys.version_info[:2])')
        gams_ver=api
        for ver in api_*; do
            if test ${ver:4} -le $py_ver; then
                gams_ver=$ver
            fi  
        done
        cd $gams_ver
        python setup.py -q install -noCheck
    - name: Install Pyomo and extensions
      run: |
        echo "Clone Pyomo-model-libraries..."
        git clone --quiet https://github.com/Pyomo/pyomo-model-libraries.git
        echo ""
        echo "Install PyUtilib..."
        echo ""
        pip install --quiet git+https://github.com/PyUtilib/pyutilib
        echo ""
        echo "Install Pyomo..."
        echo ""
        python setup.py develop # Install Pyomo
        echo ""
        echo "Install extensions..."
        echo ""
        pyomo download-extensions # Get Pyomo extensions
        pyomo build-extensions
    - name: Run nightly, not fragile tests with test.pyomo
      run: |
        echo "Run test.pyomo..."
        export PATH=$PATH:$(pwd)/gams/gams29.1_osx_x64_64_sfx/ 
        export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$(pwd)/gams/gams29.1_osx_x64_64_sfx/
        pip install nose
        KEY_JOB=1
        test.pyomo -v --cat="nightly" pyomo `pwd`/pyomo-model-libraries # Run nightly, stable tests
